import { slugify } from '@/lib/cms/utils'
import type { CmsPost, CmsProject } from '@/lib/cms/types'

function staticId(prefix: string, value: string) {
  return `${prefix}-${slugify(value)}`
}

export const fallbackPosts: CmsPost[] = [
  {
    id: staticId('post', 'From Mines To Hospitals'),
    title: 'From Mines To Hospitals: What Every Sector Gets Wrong About Tank Maintenance',
    slug: 'from-mines-to-hospitals-what-every-sector-gets-wrong-about-tank-maintenance',
    excerpt:
      'Tank maintenance failures follow predictable patterns across sectors. Understanding what goes wrong — and why — is the first step to better outcomes.',
    content:
      'Tank maintenance failures are rarely sudden. In most cases, they follow a clear pattern of missed inspections, delayed remedial work, and an underestimation of how fast corrosion or structural issues can escalate.\n\nAcross mining, government, health, and industrial sites, the common failure is not a lack of intent — it is a lack of a clear asset strategy. Operators often wait for a compliance issue, visible failure, or service interruption before intervening.\n\nThe practical fix is disciplined condition assessment, better maintenance scheduling, and early decisions about lining, repair, or replacement before the asset becomes a liability.',
    coverImageUrl: null,
    readTime: '5 min read',
    status: 'published',
    seoTitle: null,
    seoDescription: null,
    publishedAt: '2026-04-01T09:00:00.000Z',
    createdAt: '2026-04-01T09:00:00.000Z',
    updatedAt: '2026-04-01T09:00:00.000Z',
    tags: [{ id: 'tag-maintenance', name: 'Maintenance', slug: 'maintenance' }],
  },
  {
    id: staticId('post', 'Why Your Fire Tank Might Fail Compliance'),
    title: 'Why Your Fire Tank Might Fail Compliance — And How To Fix It Fast',
    slug: 'why-your-fire-tank-might-fail-compliance-and-how-to-fix-it-fast',
    excerpt:
      'AS2304 and AS1851 compliance failures in fire water systems are more common than most operators realise. Here is what to look for and how to act.',
    content:
      'Fire water compliance failures usually come from neglected inspection cycles, undocumented alterations, degraded fittings, or insufficient maintenance evidence.\n\nThe fastest path back to compliance starts with an inspection and a clear deficiency list. Once the gaps are identified, the decision becomes commercial rather than speculative: repair, reline, upgrade, or replace.\n\nFor asset owners, the key is speed and documentation. A compliant tank is not just a physical asset issue — it is a legal and insurance issue.',
    coverImageUrl: null,
    readTime: '4 min read',
    status: 'published',
    seoTitle: null,
    seoDescription: null,
    publishedAt: '2026-04-03T09:00:00.000Z',
    createdAt: '2026-04-03T09:00:00.000Z',
    updatedAt: '2026-04-03T09:00:00.000Z',
    tags: [{ id: 'tag-fire-compliance', name: 'Fire Compliance', slug: 'fire-compliance' }],
  },
  {
    id: staticId('post', 'Is Your Water Tank A Ticking Time Bomb'),
    title: 'Is Your Water Tank A Ticking Time Bomb? 5 Signs Your Tank Is Failing',
    slug: 'is-your-water-tank-a-ticking-time-bomb-5-signs-your-tank-is-failing',
    excerpt:
      'Most tank failures give warning signs long before catastrophic failure. Knowing what to look for can save significant cost and prevent compliance crises.',
    content:
      'Most failing tanks give off early warning signs: corrosion staining, leaks, unusual movement, liner degradation, damaged access components, or unexplained operational issues.\n\nThe mistake is treating these signs as isolated maintenance issues instead of indicators of a broader asset condition problem.\n\nIf multiple signs are present, the right next step is not guesswork. It is a structured inspection and a documented remediation pathway.',
    coverImageUrl: null,
    readTime: '4 min read',
    status: 'published',
    seoTitle: null,
    seoDescription: null,
    publishedAt: '2026-04-05T09:00:00.000Z',
    createdAt: '2026-04-05T09:00:00.000Z',
    updatedAt: '2026-04-05T09:00:00.000Z',
    tags: [{ id: 'tag-asset-management', name: 'Asset Management', slug: 'asset-management' }],
  },
  {
    id: staticId('post', 'Corrosion Is Killing Your Storage Tanks'),
    title: 'Corrosion Is Killing Your Storage Tanks — And Here’s How To Stop It',
    slug: 'corrosion-is-killing-your-storage-tanks-and-heres-how-to-stop-it',
    excerpt:
      'Corrosion is the single biggest threat to water storage asset longevity. Understanding the mechanisms and available solutions can extend tank life by decades.',
    content:
      'Corrosion is rarely an isolated surface issue. Left unchecked, it affects structural performance, compliance, water quality, and the total lifecycle cost of the asset.\n\nIn many cases, the best intervention is not replacement. Lining systems, targeted refurbishment, and condition-led upgrades can restore performance for a fraction of replacement cost.\n\nThe correct response depends on environment, tank condition, and stored fluid — which is why condition data matters more than assumptions.',
    coverImageUrl: null,
    readTime: '6 min read',
    status: 'published',
    seoTitle: null,
    seoDescription: null,
    publishedAt: '2026-04-07T09:00:00.000Z',
    createdAt: '2026-04-07T09:00:00.000Z',
    updatedAt: '2026-04-07T09:00:00.000Z',
    tags: [{ id: 'tag-rpvc-liners', name: 'RPVC Liners', slug: 'rpvc-liners' }],
  },
  {
    id: staticId('post', 'How RPVC Liners Extend The Life Of Aging Water Tanks'),
    title: 'How RPVC Liners Extend The Life Of Aging Water Tanks',
    slug: 'how-rpvc-liners-extend-the-life-of-aging-water-tanks',
    excerpt:
      'RPVC liner technology can restore aging tanks to full compliance and extend service life by 20+ years. Here is how the technology works and when to apply it.',
    content:
      'RPVC liners are one of the most commercially effective interventions for structurally sound tanks that have deteriorating internal surfaces or compliance risk.\n\nInstalled correctly, they isolate the stored water from the tank shell, reduce corrosion progression, and restore compliance outcomes without the cost and disruption of replacement.\n\nThey are not the answer for every asset, but where the structure is still viable they can materially extend service life.',
    coverImageUrl: null,
    readTime: '5 min read',
    status: 'published',
    seoTitle: null,
    seoDescription: null,
    publishedAt: '2026-04-09T09:00:00.000Z',
    createdAt: '2026-04-09T09:00:00.000Z',
    updatedAt: '2026-04-09T09:00:00.000Z',
    tags: [{ id: 'tag-rpvc-liners-2', name: 'RPVC Liners', slug: 'rpvc-liners' }],
  },
  {
    id: staticId('post', 'Water Storage In Harsh Environments'),
    title: 'Water Storage In Harsh Environments: What You Need To Know',
    slug: 'water-storage-in-harsh-environments-what-you-need-to-know',
    excerpt:
      'Remote and harsh environments test water storage infrastructure to its limits. Specialist design, materials, and delivery capability are non-negotiable.',
    content:
      'Remote and corrosive environments expose weak specification decisions quickly. Material choice, coatings, foundations, logistics planning, and maintenance access all matter more in these conditions.\n\nAssets that perform well in metro environments often fail early in remote, coastal, mining, or chemically aggressive settings if they are not engineered for that context.\n\nThe correct solution is usually less about a product category and more about integrated engineering and delivery planning.',
    coverImageUrl: null,
    readTime: '5 min read',
    status: 'published',
    seoTitle: null,
    seoDescription: null,
    publishedAt: '2026-04-11T09:00:00.000Z',
    createdAt: '2026-04-11T09:00:00.000Z',
    updatedAt: '2026-04-11T09:00:00.000Z',
    tags: [{ id: 'tag-remote-projects', name: 'Remote Projects', slug: 'remote-projects' }],
  },
]

export const fallbackProjects: CmsProject[] = [
  {
    id: staticId('project', 'Borumba Hydro Scheme'),
    title: 'Borumba Hydro Scheme',
    slug: 'borumba-hydro',
    summary: '2 × 521KL tanks — potable and effluent dual-purpose system',
    content:
      'Pacific Water Tanks delivered two 521KL tanks for the Borumba Hydro Scheme, combining potable and effluent storage requirements into a coordinated infrastructure outcome.\n\nThe project required design integration, remote site planning, and disciplined delivery sequencing to fit the broader energy program.',
    sector: 'Hydro Energy / Government',
    location: 'Borumba Dam, QLD',
    scope: '2 × 521KL tanks — potable and effluent dual-purpose system',
    heroImageUrl: '/projects/borumba-01.jpg',
    galleryUrls: ['/projects/borumba-01.jpg', '/projects/borumba-02.jpg', '/projects/borumba-03.jpg'],
    status: 'published',
    featured: true,
    seoTitle: null,
    seoDescription: null,
    publishedAt: '2026-04-01T09:00:00.000Z',
    createdAt: '2026-04-01T09:00:00.000Z',
    updatedAt: '2026-04-01T09:00:00.000Z',
    tags: [{ id: 'tag-government', name: 'Government', slug: 'government' }],
  },
  {
    id: staticId('project', 'Hobart Nyrstar Industrial'),
    title: 'Hobart Nyrstar Industrial',
    slug: 'hobart-nyrstar',
    summary: 'Industrial tank refurbishment for a zinc processing environment',
    content:
      'Hobart Nyrstar required an outcome suited to a corrosion-critical industrial environment. Pacific Water Tanks delivered a refurbishment-led solution aligned to the operating conditions of the facility.\n\nThe project highlights the need for sector-specific material and maintenance decisions in aggressive process environments.',
    sector: 'Refurbish',
    location: 'Hobart, Tasmania',
    scope: 'Industrial tank refurbishment for a zinc processing environment',
    heroImageUrl: '/projects/hobart-01.jpg',
    galleryUrls: ['/projects/hobart-01.jpg', '/projects/hobart-02.jpg', '/projects/hobart-03.jpg'],
    status: 'published',
    featured: true,
    seoTitle: null,
    seoDescription: null,
    publishedAt: '2026-04-02T09:00:00.000Z',
    createdAt: '2026-04-02T09:00:00.000Z',
    updatedAt: '2026-04-02T09:00:00.000Z',
    tags: [{ id: 'tag-refurbish', name: 'Refurbish', slug: 'refurbish' }],
  },
  {
    id: staticId('project', 'Doomadgee 2ML Reservoir'),
    title: 'Doomadgee 2ML Reservoir',
    slug: 'doomadgee-wtp',
    summary: '2ML ground-level reservoir for remote community water storage',
    content:
      'Pacific Water Tanks delivered a 2ML ground-level reservoir in Doomadgee as part of remote community water infrastructure delivery.\n\nThe project required remote logistics, community-aware delivery planning, and coordination around challenging site conditions.',
    sector: 'Remote Community / Government',
    location: 'Doomadgee, QLD (Remote)',
    scope: '2ML ground-level reservoir for remote community water storage',
    heroImageUrl: '/projects/doomadgee-04.jpg',
    galleryUrls: ['/projects/doomadgee-04.jpg', '/projects/doomadgee-05.jpg', '/projects/doomadgee-06.jpg'],
    status: 'published',
    featured: true,
    seoTitle: null,
    seoDescription: null,
    publishedAt: '2026-04-03T09:00:00.000Z',
    createdAt: '2026-04-03T09:00:00.000Z',
    updatedAt: '2026-04-03T09:00:00.000Z',
    tags: [
      { id: 'tag-government-2', name: 'Government', slug: 'government' },
      { id: 'tag-remote-community', name: 'Remote Community', slug: 'remote-community' },
    ],
  },
  {
    id: staticId('project', 'Albury Reservoir Reline'),
    title: 'Albury Reservoir Reline',
    slug: 'albury-reservoir',
    summary: '600kL reservoir RPVC reline and full refurbishment',
    content:
      'Pacific Water Tanks completed a full refurbishment and RPVC relining scope for an aging municipal reservoir in Albury.\n\nThe project is a strong example of lining as a lifecycle extension strategy when the core structure remains sound.',
    sector: 'Municipal / Government',
    location: 'Albury, NSW',
    scope: '600kL reservoir RPVC reline and full refurbishment',
    heroImageUrl: '/projects/albury-01.jpg',
    galleryUrls: ['/projects/albury-01.jpg'],
    status: 'published',
    featured: false,
    seoTitle: null,
    seoDescription: null,
    publishedAt: '2026-04-04T09:00:00.000Z',
    createdAt: '2026-04-04T09:00:00.000Z',
    updatedAt: '2026-04-04T09:00:00.000Z',
    tags: [
      { id: 'tag-government-3', name: 'Government', slug: 'government' },
      { id: 'tag-rpvc-liners-project', name: 'RPVC Liners', slug: 'rpvc-liners' },
      { id: 'tag-tank-liners', name: 'Tank Liners', slug: 'tank-liners' },
      { id: 'tag-refurbish-2', name: 'Refurbish', slug: 'refurbish' },
    ],
  },
  {
    id: staticId('project', 'Clarence Road Liner Replacement'),
    title: 'Clarence Road Liner Replacement',
    slug: 'clarence-road-liner',
    summary: '2 × tank RPVC liner replacement',
    content:
      'Pacific Water Tanks replaced failing liners for two tanks at 107 Clarence Road, restoring compliant operation and extending usable life.\n\nThis project reflects a common remediation pathway for commercial assets that need practical intervention without full replacement.',
    sector: 'Commercial',
    location: '107 Clarence Road',
    scope: '2 × tank RPVC liner replacement',
    heroImageUrl: '/projects/clarence-01.jpg',
    galleryUrls: ['/projects/clarence-01.jpg', '/projects/clarence-02.jpg', '/projects/clarence-03.jpg'],
    status: 'published',
    featured: false,
    seoTitle: null,
    seoDescription: null,
    publishedAt: '2026-04-05T09:00:00.000Z',
    createdAt: '2026-04-05T09:00:00.000Z',
    updatedAt: '2026-04-05T09:00:00.000Z',
    tags: [
      { id: 'tag-commercial', name: 'Commercial', slug: 'commercial' },
      { id: 'tag-fire-contractors', name: 'Fire Contractors', slug: 'fire-contractors' },
      { id: 'tag-rpvc-liners-project-2', name: 'RPVC Liners', slug: 'rpvc-liners' },
      { id: 'tag-tank-liners-2', name: 'Tank Liners', slug: 'tank-liners' },
    ],
  },
]
