import { slugify } from '@/lib/cms/utils'
import type { CmsPost, CmsProject } from '@/lib/cms/types'

function staticId(prefix: string, value: string) {
  return `${prefix}-${slugify(value)}`
}

const BASE = 'https://mhggidgfivmdgkjerejn.supabase.co/storage/v1/object/public/cms-media/posts'

export const fallbackPosts: CmsPost[] = [
  {
    id: staticId('post', 'Water Is Food Your Tank Is The Crockery'),
    title: 'Water is Food: Your Tank is the Crockery',
    slug: 'water-is-food-your-tank-is-the-crockery',
    excerpt:
      'Water is food — literally. We pipe it into people\'s homes 24 hours a day, which means the vessel it\'s stored in matters as much as the source.',
    content:
      'Water is food. Not metaphorically — literally. We pipe it into people\'s homes and serve it up 24 hours a day. Which means the vessel it\'s stored in matters as much as what\'s in it.\n\nThink of it this way: your water treatment plant is the kitchen. The distribution system is the crockery. Anyone who\'s watched Ramsay\'s Kitchen Nightmares knows that a brilliant kitchen can still send people to hospital if the plates are dirty. The same logic applies to every storage tank in Australia.\n\nAcross Australia, there are thousands of potable water storage tanks that have never been properly assessed. Tanks with cracked roofs where birds roost and leave waste behind. Tanks with corroded walls leaching iron into treated drinking water. Tanks whose liners failed years ago, silently.\n\nThe difference between a dirty plate and a dirty tank? You can see the plate. Most Australians have no idea what condition the vessel holding their drinking water is in — and in many cases, neither do the asset owners.\n\nProactive maintenance isn\'t expensive — deferred maintenance is. A tank that receives regular inspection and cleaning costs a fraction of one that requires emergency remediation or full replacement. The restaurants that make their customers sick don\'t stay in business long. The water industry works the same way.\n\nThe question isn\'t whether your tank is at risk. It\'s whether you know the condition it\'s in right now — and whether that would hold up if someone looked inside.\n\nIn Australia, potable water storage tanks sit between the treatment plant and the tap — but unlike the plant itself, many are never formally inspected. A tank with a cracked roof or failed liner can silently re-contaminate treated water over months or years. Proactive inspection and maintenance is not optional infrastructure spending; it is the last line of defence before the tap.\n\nFor fire water storage tanks, AS1851-2012 mandates routine inspection at defined intervals. For potable storage tanks, most Australian water authorities target inspection cycles of 1–4 years depending on tank size, condition history, and risk rating.',
    coverImageUrl: `${BASE}/water-food-hero.jpg`,
    readTime: '2 min read',
    status: 'published',
    seoTitle: 'Water is Food: Your Tank is the Crockery | PC Water Infrastructure',
    seoDescription: 'Water is food — and your storage tank is what it\'s served on. A short, sharp look at why the vessel matters as much as the source.',
    publishedAt: '2026-04-14T09:00:00.000Z',
    createdAt: '2026-04-14T09:00:00.000Z',
    updatedAt: '2026-04-14T09:00:00.000Z',
    tags: [
      { id: 'tag-tank-maintenance-wf', name: 'Tank Maintenance', slug: 'tank-maintenance' },
      { id: 'tag-potable-water', name: 'Potable Water', slug: 'potable-water' },
      { id: 'tag-compliance-wf', name: 'Compliance', slug: 'compliance' },
    ],
  },
  {
    id: staticId('post', 'From Mines To Hospitals'),
    title: 'From Mines to Hospitals: What Every Sector Gets Wrong About Tank Maintenance',
    slug: 'from-mines-to-hospitals-what-every-sector-gets-wrong-about-tank-maintenance',
    excerpt:
      'Every industry depends on water storage — and every sector repeats the same maintenance mistakes. Five critical errors that shorten tank life, compromise water quality, and create compliance risk.',
    content:
      'Every industry depends on water storage in one way or another. From the massive tanks keeping mine sites operational, to the potable water reserves that safeguard hospitals and schools, tanks are the silent backbone of commercial, industrial, and public facilities. Yet across sectors, the same critical mistakes are repeated time and time again. These errors shorten tank life, compromise water quality, and create unnecessary risks to safety, compliance, and budgets.\n\nThe Australian water industry applies a useful benchmark to stored water: treat it like a food-grade product — with the same standards applied to milk, wine, and grain storage. You wouldn\'t leave an unlocked milk vat uninspected for a decade. But that is effectively what happens with thousands of water storage assets across the country every year. The result is a risk level that engineers have a name for: ROL — Running on Luck.\n\nToo often, organisations view tanks as once-off investments. Install them, fill them, forget about them. The reality is that tanks are not static assets — they are systems made up of multiple interacting layers, each of which degrades on a different schedule. When a tank is neglected, these layers don\'t all fail at once — they fail quietly and at different rates, making the deterioration hard to detect until it becomes severe.\n\nStandards like AS 1851 require routine inspection and documented service logs. Yet across hospitals, schools, councils, and commercial buildings, inspection schedules are routinely skipped — and when regulators or insurers request proof, the paperwork is missing. Two practices separate effective inspection programs from paper exercises: sequential photography at fixed reference points, and fresh eyes from an independent inspector who hasn\'t normalised the gradual decline.\n\nEvery sector faces unique environmental and operational stresses. Mining tanks are not hospital tanks. Neither should be maintained like one. Mining environments suffer from high-dust ventilation failures, dissimilar metal corrosion, and temperature cycling on RPVC liners. Hospital platforms and hatch areas are the most common contamination entry point — not the water source itself. Agriculture faces UV degradation and seasonal fluctuation stress on liner seams.\n\nQuick fixes, mismatched materials, and off-spec repairs create the appearance of rectification while the real problem continues beneath the surface. The single most important factor in coating performance is not the coating — it is surface preparation. A coating applied over contaminated or inadequately profiled steel will fail years ahead of schedule regardless of the product specification.\n\nThe most expensive maintenance decision is always the one made after the failure. Waiting until a problem becomes visible is the default mode for many organisations, despite the well-understood cost premium of reactive repair over planned maintenance. Tanks without active inspection programs are not on a maintenance schedule — they are running on luck.\n\nAvoiding these mistakes requires discipline around a small number of well-understood maintenance activities, applied consistently: independent professional inspection every 1–4 years, sequential photography at every inspection, cleaning and desludging every 4–6 years for treated water, annual overflow pipe and outlet screen verification, and a single-mobilisation approach that addresses internal coating and entry point drainage simultaneously.\n\nFor mining and resource operations, cathodic protection systems require the same scheduled attention as the tanks themselves — anode replacement cycles of 8–15 years must be built into the maintenance register, not discovered during an emergency inspection. Cathodic protection installed too late, after significant wall thinning, becomes a band-aid rather than a genuine corrosion prevention measure.\n\nFor public facilities, overflow pipework provides a warm, sheltered habitat for vermin. Animal carcasses entering tanks through unsealed overflow pipes are a documented contamination source in the Australian water industry. Roof drain connection failures — where drainage is inadvertently routed into the tank rather than away — have contaminated public supply tanks for years before discovery.\n\nWater stagnation in low-turnover zones creates conditions where bacteria breed and disinfection residuals deplete. Evidence of poor turnover is visible during inspection: sediment layer patterns on the tank floor, algae growth on lower wall surfaces, and flow-direction staining. SCADA-integrated flow monitoring can detect abnormal turnover rates remotely before conditions deteriorate to the point requiring emergency intervention.\n\nThe correct response to these challenges is a structured asset management program — not guesswork. Condition data drives better decisions than assumptions, and the organisations that catch failures early are consistently the ones that treat tanks with the same seriousness as pumps, generators, and other mission-critical infrastructure.\n\nFor a detailed breakdown of corrosion types, cathodic protection strategy, and epoxy versus RPVC coating selection, see our article on how to stop corrosion killing your water storage tanks.',
    coverImageUrl: `${BASE}/sector-hero.jpg`,
    readTime: '9 min read',
    status: 'published',
    seoTitle: 'From Mines to Hospitals: What Every Sector Gets Wrong About Tank Maintenance',
    seoDescription:
      'Every sector depends on water storage and every sector repeats the same maintenance mistakes. Discover the five critical errors costing asset owners in Australia.',
    publishedAt: '2026-04-01T09:00:00.000Z',
    createdAt: '2026-04-01T09:00:00.000Z',
    updatedAt: '2026-04-01T09:00:00.000Z',
    tags: [
      { id: 'tag-maintenance', name: 'Tank Maintenance', slug: 'tank-maintenance' },
      { id: 'tag-asset-mgmt-mh', name: 'Asset Management', slug: 'asset-management' },
      { id: 'tag-compliance-mh', name: 'Compliance', slug: 'compliance' },
    ],
  },
  {
    id: staticId('post', 'Why Your Fire Tank Might Fail Compliance'),
    title: 'Why Your Fire Tank Might Fail Compliance — And How to Fix It Fast',
    slug: 'why-your-fire-tank-might-fail-compliance-and-how-to-fix-it-fast',
    excerpt:
      'Many Australian fire tanks fail AS 2304 and AS 1851 compliance without owners realising. Understand the common causes, real costs, and how to get back to compliance fast.',
    content:
      'When it comes to fire safety, cutting corners is not an option. Yet across Australia, countless facilities are running fire protection systems that do not meet current standards. The stakes could not be higher. A non-compliant fire tank does not just risk fines and insurance headaches — it could mean lives lost and property destroyed in an emergency.\n\nTwo standards govern fire water storage tanks in Australia. AS 2304 covers the design, fabrication, and installation of water storage tanks specifically for fire protection — including capacity, materials, fittings, and access. AS 1851 governs the routine service of fixed fire protection systems, mandating inspection intervals, testing requirements, and documented maintenance records. Together, these two standards define what a compliant fire tank looks like at installation, and what keeping it compliant requires throughout its operational life.\n\nFire tanks fail compliance for a consistent set of reasons. Tank capacity is insufficient for the calculated demand — particularly common where hazard classifications have changed since original installation. Fittings, pipework, and valves are degraded, corroded, or incompatible with current standards. Internal coatings and liners have deteriorated beyond the acceptable condition threshold for AS 2304 materials. Inspection and service records are incomplete, missing mandatory test results, or have lapsed beyond the required intervals under AS 1851.\n\nPhysical failure modes include corrosion of inlet and outlet pipework, blocked strainers, seized valves, and damaged access hatches that compromise the integrity of stored water. In tanks that have been out of routine service for several cycles, sediment accumulation and biofilm growth add contamination risk to the structural concerns.\n\nThe cost of non-compliance extends beyond regulatory penalties. Insurance claims may be denied where fire protection systems are found non-compliant at the time of a loss event. Principal contractor liability under building and fire codes can attach where compliance documentation is absent. In healthcare, education, and government facilities, non-compliance triggers mandatory reporting obligations and operational restrictions.\n\nThe fastest path back to compliance starts with an independent inspection and a documented deficiency register. Once the gaps are identified, the decision becomes commercial rather than speculative: repair, reline, upgrade, or replace. For tanks where the structure remains sound, internal relining under AS 2304-compliant materials is consistently the most cost-effective remediation pathway.\n\nFor tanks where capacity is the primary issue, options include supplementary tank installation, pump system upgrade to increase effective available volume, or replacement with a correctly sized asset. Each pathway has a different cost, disruption, and timeline profile — which is why condition data and a clear deficiency register drive better outcomes than emergency reactive decisions.\n\nPrevention is simpler than remediation. A compliant maintenance program under AS 1851 — with documented inspection records, test results, and deficiency tracking — keeps fire tanks in the window where issues are addressable at routine maintenance cost, not emergency remediation cost. The organisations that avoid compliance emergencies are consistently the ones that treat their fire tanks as active safety assets, not set-and-forget infrastructure.\n\nAnnual inspection under AS 1851 is not a formality — it is the mechanism that keeps tanks in the condition range where compliance is achievable and affordable. Tanks that fall out of routine service cycles consistently present more deficiencies at greater remediation cost when they are eventually assessed.\n\nPC Water Infrastructure provides inspection, condition assessment, and remediation for fire water storage tanks across Australia — including RPVC relining, pipework replacement, valve servicing, and full compliance documentation to support AS 2304 and AS 1851 obligations.\n\nFor a related breakdown of how internal corrosion develops and what coating systems are appropriate for fire tank environments, see our article on stopping corrosion in water storage tanks.',
    coverImageUrl: `${BASE}/fire-tank-hero.jpg`,
    readTime: '6 min read',
    status: 'published',
    seoTitle: 'Why Your Fire Tank Might Fail Compliance — And How to Fix It Fast | PC Water Infrastructure',
    seoDescription:
      'Many Australian fire tanks fail AS 2304 and AS 1851 compliance without owners realising. Understand the common causes, real costs, and how to fix issues fast.',
    publishedAt: '2026-04-03T09:00:00.000Z',
    createdAt: '2026-04-03T09:00:00.000Z',
    updatedAt: '2026-04-03T09:00:00.000Z',
    tags: [
      { id: 'tag-fire-compliance', name: 'Fire Compliance', slug: 'fire-compliance' },
      { id: 'tag-compliance-fc', name: 'Compliance', slug: 'compliance' },
      { id: 'tag-tank-maintenance-fc', name: 'Tank Maintenance', slug: 'tank-maintenance' },
    ],
  },
  {
    id: staticId('post', 'Is Your Water Tank A Ticking Time Bomb'),
    title: 'Is Your Water Tank a Ticking Time Bomb? 5 Signs Your Tank Is Failing',
    slug: 'is-your-water-tank-a-ticking-time-bomb-5-signs-your-tank-is-failing',
    excerpt:
      'Most tank failures give warning signs long before catastrophic failure. Five proven indicators that your water storage asset needs immediate professional attention.',
    content:
      'Water tanks are the unsung heroes of countless industries, homes, and facilities — quietly ensuring water is stored and ready whenever it\'s needed. Steel, concrete, and polyethylene tanks all face the same reality: they degrade over time, and when they fail, the consequences are costly, disruptive, and sometimes dangerous.\n\nThe Australian water industry has a useful benchmark for how stored water should be treated: like a food-grade product. You wouldn\'t leave an unlocked milk vat uninspected for a decade. Yet that is effectively what happens with thousands of water storage assets across the country. The warning signs are there — but only if you know what to look for.\n\nVisible corrosion is the most obvious sign — but it is rarely limited to what you can see on the surface. Rust streaks running down external walls, around fittings, or near overflow outlets signal surface corrosion. Inside the tank, brown, reddish, or cloudy water indicates internal steel components are breaking down. Blisters and bubbles beneath a coating are caused by sub-film corrosion — pitting that concentrates attack into small, deep zones that compromise structural integrity faster than surface rust. For potable water tanks under AS4020, discolouration is a non-negotiable trigger for immediate inspection.\n\nUnusual odours or changes in water colour, taste, or clarity are direct indicators of contamination in the stored water. A tank with a damaged roof, corroded lining, or cracked access hatch can allow animal entry, sediment accumulation, and chemical leaching into treated drinking water. Hydrogen sulphide odour signals bacterial activity — particularly sulphate-reducing bacteria that attack the tank substrate at the molecular level, creating pitting that is often invisible until significant material loss has occurred.\n\nLeakage or damp patches around the tank base, at seams, or near foundation joints are a sign of structural compromise. If your tank is losing water without a visible external leak, internal corrosion may have created perforations. Even minor pitting can cause slow losses that go unnoticed for months. Moisture at the tank base — particularly near seams, welds, or where the tank meets the foundation slab — signals a potential breach. These zones are prone to sediment accumulation and condensation, making them a common first failure point.\n\nInconsistent water pressure or unexpected flow variations can indicate partial blockages, valve issues, or sediment accumulation reducing effective storage volume. In fire water tanks under AS2304, pressure capacity is a compliance parameter — unexplained pressure loss triggers mandatory inspection under AS1851. Sediment that has accumulated on the tank floor reduces the available volume, affecting both pressure performance and system reliability during peak demand events.\n\nTank age alone is a risk factor, not a guarantee of failure — but material degradation timelines are well understood. Epoxy internal coatings on steel tanks have a service life of 10–15 years from application before recoating becomes necessary. Polyethylene tanks under sustained UV exposure in Australian climates degrade faster than the same tanks in sheltered environments. RPVC liner seams under temperature cycling develop micro-tears at predictable rates. If your tank is approaching or past these thresholds without a condition assessment on record, the risk profile is material.\n\nWhat these warning signs actually cost — if ignored — follows a predictable pattern. A tank inspection at the right point in the deterioration cycle typically identifies rectification options: coating reapplication, liner replacement, fitting upgrades, or targeted structural repair. The same tank identified later — after pitting has penetrated the steel, after liner seams have opened, after the roof access has allowed sustained contamination — presents a far more complex remediation scope. Industry experience consistently shows a 3–5 times cost multiplier between timely rehabilitation and emergency remediation or full replacement.\n\nAn independent inspection on a 1–4 year cycle, calibrated to the tank\'s condition and environment, is the single highest-return maintenance action available to asset owners. Pair that with ultrasonic wall thickness gauging at every inspection for steel tanks over 15 years old, and the condition history is complete enough to support genuinely data-driven maintenance decisions rather than reactive emergency responses.\n\nPC Water Infrastructure deploys ROV and UAV inspection capability capable of assessing tanks without full dewatering, reducing operational disruption while providing the condition data needed to make informed decisions. When you know exactly what condition your tank is in, every subsequent maintenance decision becomes commercial rather than speculative.\n\nIf multiple warning signs are present — corrosion, odour, leakage, pressure anomalies, and age past major maintenance thresholds — the right next step is not guesswork. It is a structured inspection and a documented remediation pathway.',
    coverImageUrl: `${BASE}/ticking-hero.jpg`,
    readTime: '5 min read',
    status: 'published',
    seoTitle: 'Is Your Water Tank a Ticking Time Bomb? 5 Signs Your Tank Is Failing',
    seoDescription:
      'Five proven warning signs your water tank is failing — corrosion, contamination, leaks, pressure loss, and age. What Australian asset owners must do before failure strikes.',
    publishedAt: '2026-04-05T09:00:00.000Z',
    createdAt: '2026-04-05T09:00:00.000Z',
    updatedAt: '2026-04-05T09:00:00.000Z',
    tags: [
      { id: 'tag-tank-maintenance-tb', name: 'Tank Maintenance', slug: 'tank-maintenance' },
      { id: 'tag-compliance-tb', name: 'Compliance', slug: 'compliance' },
      { id: 'tag-asset-management-tb', name: 'Asset Management', slug: 'asset-management' },
    ],
  },
  {
    id: staticId('post', 'Corrosion Is Killing Your Storage Tanks'),
    title: 'Corrosion Is Killing Your Storage Tanks — And Here\'s How to Stop It',
    slug: 'corrosion-is-killing-your-storage-tanks-and-heres-how-to-stop-it',
    excerpt:
      'Corrosion is the single most preventable cause of water tank failure in Australia. Learn to detect it early, choose the right coating system, and extend asset life without full replacement.',
    content:
      'Corrosion is the single most preventable cause of water tank failure across mining, industrial, and government infrastructure in Australia. When oxygen, moisture, or aggressive water chemistry contacts unprotected steel, degradation starts immediately — and accelerates without intervention. The good news: with the right inspection programme, protective coating system, and lining strategy, most tanks can be extended well beyond their original design life without full replacement.\n\nPoor pH control, aggressive chlorination, and elevated chloride concentrations all accelerate internal corrosion. Tanks storing water with a pH below 7 are particularly at risk — acidic conditions strip protective oxide layers and attack base metal directly. A common but underappreciated source of localised corrosion is the interface between pipework and the tank structure. Ductile iron pipework passing through concrete walls creates a galvanic cell where dissimilar metals meet — accelerating corrosion at the contact point. Galvanised fixtures in humid tank interiors release zinc oxide products that deplete residual chlorine, creating a direct compliance risk for potable water tanks under AS4020.\n\nCertain bacteria — particularly sulphate-reducing bacteria — metabolise sulphur compounds and produce hydrogen sulphide as a byproduct. This attacks the tank substrate at the molecular level, creating pitting that is often invisible until significant material loss has occurred. A single pinhole in an otherwise intact epoxy coating can produce more corrosion damage than an equivalent area of completely bare steel, because electrochemical current concentrates at the defect.\n\nRust streaks running down external walls, around fittings, or near overflow outlets signal surface corrosion. Inside the tank, brown, reddish, or cloudy water indicates internal steel components are breaking down. Blisters and bubbles beneath a coating are caused by sub-film corrosion — pitting that concentrates attack into small, deep zones that compromise structural integrity faster than surface rust. If your tank is losing water without a visible external leak, internal corrosion may have created perforations.\n\nUltrasonic thickness gauging measures remaining wall steel. If measurements fall below original specification, corrosion is actively consuming material. Significant thinning reduces pressure capacity and collapse resistance — particularly critical for fire tanks operating under AS2304. Pair visual checks with professional inspections on a 1–4 year cycle, more frequently in coastal, mining, or high-chloride conditions.\n\nThe single most important factor in coating system performance is not the coating — it is surface preparation. A high-quality epoxy system applied to a poorly prepared surface will fail within 2–3 years. A mid-grade epoxy applied over a correctly blasted, clean substrate will last 15 years or more. For immersed applications, coatings must be matched to the specific liquid stored. Potable water tanks require coatings compliant with AS4020, whilst wastewater or chemical storage tanks require chemical resistance data matched to the stored substance.\n\nRPVC liners and Glass Reinforced Plastic liners are the most cost-effective life-extension solution for ageing steel and concrete tanks. The liner creates a physical barrier between the stored water and the tank substrate — eliminating direct contact and halting internal corrosion entirely. PC Water Infrastructure has installed RPVC liners across town reservoirs for the Northern Peninsula Area Regional Council, health facilities, and mine sites including projects for Rio Tinto, BHP, and Veolia.\n\nCathodic protection works by making the tank\'s steel structure the cathode in an electrochemical circuit, preventing oxidation. Timing is critical — installed too early it provides little benefit, installed too late it cannot recover lost material. The best outcomes occur when cathodic protection is incorporated into a maintenance programme alongside a quality coating system, deployed at the point where coating holiday density starts to increase during routine inspection cycles.\n\nIndependent inspectors with fresh eyes on an asset detect gradual changes that familiar operators miss. PC Water Infrastructure deploys ROV and UAV underwater drones and diving inspection teams capable of assessing tanks without full dewatering, minimising operational disruption. Ultrasonic wall thickness gauging at every inspection is recommended for steel tanks over 15 years old.\n\nCorrosion does not automatically mean replacement. Refurbishment typically costs 30–60% of full replacement and can add 20–30 years to an asset\'s service life. For new or replacement tanks, the right material selection — fibreglass, HDPE, stainless steel, or concrete with appropriate internal protection — eliminates most corrosion risk at source.\n\nSteel tanks in Australian industrial and mining environments face some of the most aggressive corrosion conditions on the continent — high humidity, thermal cycling, aggressive water chemistry, and MIC-active soils. The difference between a tank that lasts 20 years and one that lasts 60 years typically comes down to three decisions: the coating system selected at installation, the quality of surface preparation, and whether the asset owner implements a regular independent inspection programme.\n\nA practical corrosion prevention checklist: annual visual inspection of accessible external surfaces; professional internal inspection every 1–4 years calibrated to condition; ultrasonic wall thickness gauging at each inspection for steel tanks over 15 years; coating system renewal before holiday density exceeds 5% of surface area; cathodic protection anode replacement on schedule; and outlet screen replacement from galvanised to HDPE at first internal renovation.',
    coverImageUrl: `${BASE}/corrosion-hero.jpg`,
    readTime: '7 min read',
    status: 'published',
    seoTitle: 'Corrosion Is Killing Your Storage Tanks — And Here\'s How to Stop It',
    seoDescription:
      'Corrosion is the leading cause of premature tank failure in Australia. Learn to detect it early, choose the right coating, and extend asset life without full replacement.',
    publishedAt: '2026-04-07T09:00:00.000Z',
    createdAt: '2026-04-07T09:00:00.000Z',
    updatedAt: '2026-04-07T09:00:00.000Z',
    tags: [
      { id: 'tag-corrosion', name: 'Corrosion', slug: 'corrosion' },
      { id: 'tag-rpvc-liners', name: 'RPVC Liners', slug: 'rpvc-liners' },
      { id: 'tag-asset-management', name: 'Asset Management', slug: 'asset-management' },
    ],
  },
  {
    id: staticId('post', 'How RPVC Liners Extend The Life Of Aging Water Tanks'),
    title: 'How RPVC Liners Extend the Life of Aging Water Tanks',
    slug: 'how-rpvc-liners-extend-the-life-of-aging-water-tanks',
    excerpt:
      'Aging water storage tanks don\'t always need replacing. RPVC liners extend tank service life by 10–20 years at a fraction of replacement cost — while meeting AS2304 and AS1851 compliance requirements.',
    content:
      'Aging water storage tanks are reaching the end of their service life across Australia. RPVC liners offer a proven third path — extending service life by 10 to 20 years at a fraction of replacement cost, while restoring compliance with AS2304, AS1851, and AS4020 requirements. For asset owners managing concrete and steel tanks approaching the end of viable internal coating cycles, RPVC lining is the decision worth understanding in detail.\n\nMining operations, remote communities, and municipal utilities all face the same pattern: internal corrosion progressing unchecked, AS1851 inspection cycles revealing escalating deficiency counts, and a growing gap between the tank\'s current condition and what compliance requires. The choice appears to be full replacement at high cost, or ongoing reactive repair that never addresses the root cause. RPVC lining is a third option that asset owners frequently underutilise.\n\nAn RPVC liner is a rigid polyvinyl chloride membrane installed inside an existing tank, bonded to the internal wall surface and sealed at all penetrations. It creates a complete physical barrier between the stored water and the tank substrate — ending direct contact between water and the corroding surface. Unlike internal coatings, which require blast-clean, application, and reapplication cycles, a correctly installed RPVC liner is a one-time installation with a design life that typically exceeds 20 years.\n\nCorrosion is not just a structural problem — it is a water quality problem. Internal corrosion in steel tanks introduces iron, zinc, and other metal compounds into stored water. In potable water tanks governed by AS4020, these contamination pathways create direct compliance failures. In fire water tanks under AS2304, corrosion reduces the structural integrity of the vessel and the reliability of the system under demand. RPVC lining eliminates both pathways simultaneously.\n\nThe case for RPVC liners rests on four factors. Cost: relining consistently costs 30–50% of full tank replacement, with significantly lower disruption to site operations. Compliance: RPVC materials used in potable water applications are AS4020 certified, restoring the tank\'s compliance status without a new asset. Service life: design life of 20+ years from installation, with no recoating cycles. Speed: a typically sized water tank can be lined within 2–5 days of dewatering and internal preparation, versus weeks for replacement.\n\nPC Water Infrastructure completed RPVC liner installations for six town reservoirs for the Northern Peninsula Area Regional Council in Far North Queensland — a remote, high-humidity environment with aggressive water chemistry. The reservoirs were assessed, dewatered, blast-cleaned, and lined under a single mobilisation program, restoring compliance across all six assets within the project schedule. The alternative — replacement — would have required significantly longer lead times and substantially higher capital expenditure for a remote community with limited infrastructure budget.\n\nThe installation process follows a consistent sequence: dewatering and confined space preparation to AS2865; surface blast-cleaning to Sa2.5 standard; primer application to the prepared substrate; RPVC sheet installation and bonding; sealing of all penetrations including inlet, outlet, overflow, and scour connections; final inspection and pressure testing. A correctly executed installation leaves no unsupported liner sections, no voids behind the membrane, and no unsealed penetration points — each of which is a potential failure initiation site if the installation quality is poor.\n\nRPVC liners make the most difference in three scenarios: steel tanks where the structural shell remains sound but internal coatings have failed beyond economic reapplication; concrete tanks where joint sealant failures and surface carbonation have created contamination pathways; and older bolted steel panel tanks where individual panel replacements are no longer cost-effective but the bolt pattern structure remains intact. In each case, the liner works with the existing structure rather than replacing it.\n\nThe comparison against alternatives is consistent across project types. Epoxy recoating requires full blast-clean and is effective for 10–15 years before the cycle repeats. GRP lining offers similar protection to RPVC but at higher material and installation cost. Full replacement delivers a new asset lifespan but at 2–3 times the capital cost and with significantly greater operational disruption. For tanks where the question is whether to spend heavily now on replacement or find a compliant pathway that extends the existing asset, RPVC lining is the answer that asset managers consistently return to when they have good condition data to work with.\n\nFor an accurate assessment of whether your tank is a candidate for RPVC relining, the starting point is always an independent condition inspection. The inspection determines whether the structural shell can support a liner installation, identifies the penetration configuration, and provides the deficiency register that informs the relining scope. Contact PC Water Infrastructure to arrange an inspection and relining assessment for your site.',
    coverImageUrl: `${BASE}/rpvc-hero.jpg`,
    readTime: '5 min read',
    status: 'published',
    seoTitle: 'How RPVC Liners Extend the Life of Aging Water Tanks | PC Water Infrastructure',
    seoDescription:
      'Aging water storage tanks don\'t always need replacing. RPVC liners extend tank service life by 10–20 years at a fraction of replacement cost.',
    publishedAt: '2026-04-09T09:00:00.000Z',
    createdAt: '2026-04-09T09:00:00.000Z',
    updatedAt: '2026-04-09T09:00:00.000Z',
    tags: [
      { id: 'tag-rpvc-liners-2', name: 'RPVC Liners', slug: 'rpvc-liners' },
      { id: 'tag-tank-maintenance-rpvc', name: 'Tank Maintenance', slug: 'tank-maintenance' },
      { id: 'tag-asset-management-rpvc', name: 'Asset Management', slug: 'asset-management' },
    ],
  },
  {
    id: staticId('post', 'Water Storage In Harsh Environments'),
    title: 'Water Storage in Harsh Environments: What You Need to Know',
    slug: 'water-storage-in-harsh-environments-what-you-need-to-know',
    excerpt:
      'Mining zones, island communities, remote outback — water storage in harsh Australian environments demands more than standard design. Here\'s what actually works in the field.',
    content:
      'When most people think about water tanks, they picture something simple. But in mining zones, remote communities, and harsh climates across Australia, water storage is one of the most technically demanding infrastructure challenges a project can face. The environment exposes every weak specification decision quickly — and the cost of failure is measured not just in dollars, but in operational shutdowns and community water security.\n\nIn remote locations, tanks store fire protection reserves, potable water, and processing supplies. There is no local trade supplier, no quick callout, and no redundancy if the primary storage fails. The tank has to work — reliably, in conditions that would defeat standard design assumptions — and when it needs maintenance, that maintenance has to be achievable under the access and logistics constraints of the site.\n\nHarsh environments expose weaknesses that controlled conditions would never reveal. UV degradation on polyethylene tanks in Australian climates significantly reduces service life compared to manufacturer expectations derived from temperate environment testing. High-dust conditions in mining zones cause turbine ventilation units to seize, leaving tanks fully open to vermin and contamination. Temperature cycling in remote outback environments — where ambient temperatures swing 40 degrees between day and night — stresses liner seams, joint sealants, and base fittings at rates that standard design cycles do not account for.\n\nCoastal and island environments introduce salt-laden air and elevated chloride exposure. In these conditions, standard galvanised components corrode within seasons. Dissimilar metal connections corrode at accelerated rates. Roof fixings and access ladder brackets that would last decades in a temperate environment become replacement items within years. Material specification in these environments must account for the actual exposure profile, not the generic Australian standard.\n\nInspection in remote environments presents its own challenge. Full dewatering is not always operationally viable — the tank cannot be taken out of service for the duration required by a conventional inspection approach. PC Water Infrastructure deploys ROV and UAV inspection technology capable of assessing tank internal and external condition without dewatering, providing the same condition data — wall thickness readings, coating condition mapping, penetration seal assessment — that a drained inspection would deliver, without the operational disruption.\n\nProjects from the field demonstrate what the right approach looks like. The Doomadgee reservoir project in remote Far North Queensland required remote logistics planning, community-aware delivery scheduling, and coordination around challenging site conditions without the infrastructure margins available on urban projects. The Borumba Hydro Scheme in South East Queensland required dual-purpose potable and effluent storage systems integrated into a broader energy infrastructure program — where delivery sequencing had to fit the construction critical path, not just the tank installation schedule.\n\nThe Northern Peninsula Area Regional Council reservoir relining program — six town water reservoirs across a remote Far North Queensland region — demonstrates how a structured, multi-asset mobilisation approach delivers better outcomes than individual reactive responses. Assessing all six assets under a single inspection program, then executing relining under a single mobilised trade team, achieved cost efficiencies and quality consistency that individual site responses could not have matched.\n\nThe design principles that separate tanks that perform in harsh conditions from those that fail early are consistent: material selection matched to the actual exposure profile; coating and liner systems rated for the temperature range and water chemistry of the specific site; structural design accounting for the access and maintenance constraints of the location; and commissioning that includes a documented baseline condition assessment — so the first inspection has a reference point to compare against, rather than starting from an unknown.\n\nFor new installations in remote or harsh environments, the procurement decision is as important as the engineering. A tank specified correctly for the environment and installed with the right materials and quality controls will cost more at procurement than a standard specification. The difference is recovered many times over in extended service life, reduced maintenance frequency, and avoided emergency remediation costs — especially in remote locations where every mobilisation carries a significant logistics cost.\n\nPC Water Infrastructure has delivered water storage infrastructure in remote Far North Queensland, island communities, mining operations, and harsh outback environments across Australia. If you are planning a new installation or assessing an existing asset in a challenging environment, the starting point is always condition data and site-specific specification — not a catalogue selection.',
    coverImageUrl: `${BASE}/harsh-env-hero.jpg`,
    readTime: '6 min read',
    status: 'published',
    seoTitle: 'Water Storage in Harsh Environments: What You Need to Know | PC Water Infrastructure',
    seoDescription:
      'Mining zones, island communities, remote outback — water storage in harsh Australian environments demands more than standard design.',
    publishedAt: '2026-04-11T09:00:00.000Z',
    createdAt: '2026-04-11T09:00:00.000Z',
    updatedAt: '2026-04-11T09:00:00.000Z',
    tags: [
      { id: 'tag-remote-projects', name: 'Remote Projects', slug: 'remote-projects' },
      { id: 'tag-asset-management-he', name: 'Asset Management', slug: 'asset-management' },
      { id: 'tag-tank-maintenance-he', name: 'Tank Maintenance', slug: 'tank-maintenance' },
    ],
  },
]

export const fallbackProjects: CmsProject[] = [
  {
    id: staticId('project', 'Borumba Hydro Scheme'),
    title: 'Borumba Hydro Scheme',
    slug: 'borumba-hydro',
    summary: '2 × 521KL tanks — potable and effluent dual-purpose system',
    content:
      'PC Water Infrastructure delivered two 521KL tanks for the Borumba Hydro Scheme, combining potable and effluent storage requirements into a coordinated infrastructure outcome.\n\nThe project required design integration, remote site planning, and disciplined delivery sequencing to fit the broader energy program.',
    sector: 'Hydro Energy / Government',
    location: 'Borumba Dam, QLD',
    scope: '2 × 521KL tanks — potable and effluent dual-purpose system',
    heroImageUrl: 'https://goldengraphixstudios.github.io/pc-water/projects/borumba-01.jpg',
    galleryUrls: [
      'https://goldengraphixstudios.github.io/pc-water/projects/borumba-01.jpg',
      'https://goldengraphixstudios.github.io/pc-water/projects/borumba-02.jpg',
      'https://goldengraphixstudios.github.io/pc-water/projects/borumba-03.jpg',
      'https://goldengraphixstudios.github.io/pc-water/projects/borumba-04.jpg',
      'https://goldengraphixstudios.github.io/pc-water/projects/borumba-05.jpg',
      'https://goldengraphixstudios.github.io/pc-water/projects/borumba-06.jpg',
    ],
    status: 'published',
    featured: true,
    seoTitle: null,
    seoDescription: null,
    publishedAt: '2026-04-01T09:00:00.000Z',
    createdAt: '2026-04-01T09:00:00.000Z',
    updatedAt: '2026-04-01T09:00:00.000Z',
    tags: [{ id: 'tag-government', name: 'Government', slug: 'government' }],
  },
  {
    id: staticId('project', 'Hobart Nyrstar Industrial'),
    title: 'Hobart Nyrstar Industrial',
    slug: 'hobart-nyrstar',
    summary: 'Industrial tank refurbishment for a zinc processing environment',
    content:
      'Hobart Nyrstar required an outcome suited to a corrosion-critical industrial environment. PC Water Infrastructure delivered a refurbishment-led solution aligned to the operating conditions of the facility.\n\nThe project highlights the need for sector-specific material and maintenance decisions in aggressive process environments.',
    sector: 'Refurbish',
    location: 'Hobart, Tasmania',
    scope: 'Industrial tank refurbishment for a zinc processing environment',
    heroImageUrl: 'https://goldengraphixstudios.github.io/pc-water/projects/hobart-01.jpg',
    galleryUrls: [
      'https://goldengraphixstudios.github.io/pc-water/projects/hobart-01.jpg',
      'https://goldengraphixstudios.github.io/pc-water/projects/hobart-02.jpg',
      'https://goldengraphixstudios.github.io/pc-water/projects/hobart-03.jpg',
      'https://goldengraphixstudios.github.io/pc-water/projects/hobart-04.jpg',
      'https://goldengraphixstudios.github.io/pc-water/projects/hobart-06.jpg',
      'https://goldengraphixstudios.github.io/pc-water/projects/hobart-07.jpg',
      'https://goldengraphixstudios.github.io/pc-water/projects/hobart-08.jpg',
      'https://goldengraphixstudios.github.io/pc-water/projects/hobart-09.jpg',
      'https://goldengraphixstudios.github.io/pc-water/projects/hobart-10.jpg',
    ],
    status: 'published',
    featured: true,
    seoTitle: null,
    seoDescription: null,
    publishedAt: '2026-04-02T09:00:00.000Z',
    createdAt: '2026-04-02T09:00:00.000Z',
    updatedAt: '2026-04-02T09:00:00.000Z',
    tags: [{ id: 'tag-refurbish', name: 'Refurbish', slug: 'refurbish' }],
  },
  {
    id: staticId('project', 'Doomadgee 2ML Reservoir'),
    title: 'Doomadgee 2ML Reservoir',
    slug: 'doomadgee-wtp',
    summary: '2ML ground-level reservoir for remote community water storage',
    content:
      'PC Water Infrastructure delivered a 2ML ground-level reservoir in Doomadgee as part of remote community water infrastructure delivery.\n\nThe project required remote logistics, community-aware delivery planning, and coordination around challenging site conditions.',
    sector: 'Remote Community / Government',
    location: 'Doomadgee, QLD (Remote)',
    scope: '2ML ground-level reservoir for remote community water storage',
    heroImageUrl: 'https://goldengraphixstudios.github.io/pc-water/projects/doomadgee-01.jpg',
    galleryUrls: [
      'https://goldengraphixstudios.github.io/pc-water/projects/doomadgee-01.jpg',
      'https://goldengraphixstudios.github.io/pc-water/projects/doomadgee-02.jpg',
      'https://goldengraphixstudios.github.io/pc-water/projects/doomadgee-03.jpg',
      'https://goldengraphixstudios.github.io/pc-water/projects/doomadgee-04.jpg',
      'https://goldengraphixstudios.github.io/pc-water/projects/doomadgee-05.jpg',
      'https://goldengraphixstudios.github.io/pc-water/projects/doomadgee-06.jpg',
      'https://goldengraphixstudios.github.io/pc-water/projects/doomadgee-07.jpg',
      'https://goldengraphixstudios.github.io/pc-water/projects/doomadgee-08.jpg',
      'https://goldengraphixstudios.github.io/pc-water/projects/doomadgee-09.jpg',
      'https://goldengraphixstudios.github.io/pc-water/projects/doomadgee-10.jpg',
    ],
    status: 'published',
    featured: true,
    seoTitle: null,
    seoDescription: null,
    publishedAt: '2026-04-03T09:00:00.000Z',
    createdAt: '2026-04-03T09:00:00.000Z',
    updatedAt: '2026-04-03T09:00:00.000Z',
    tags: [
      { id: 'tag-government-2', name: 'Government', slug: 'government' },
      { id: 'tag-remote-community', name: 'Remote Community', slug: 'remote-community' },
    ],
  },
  {
    id: staticId('project', 'Albury Reservoir Reline'),
    title: 'Albury Reservoir Reline',
    slug: 'albury-reservoir',
    summary: '600kL reservoir RPVC reline and full refurbishment',
    content:
      'PC Water Infrastructure completed a full refurbishment and RPVC relining scope for an aging municipal reservoir in Albury.\n\nThe project is a strong example of lining as a lifecycle extension strategy when the core structure remains sound.',
    sector: 'Municipal / Government',
    location: 'Albury, NSW',
    scope: '600kL reservoir RPVC reline and full refurbishment',
    heroImageUrl: 'https://goldengraphixstudios.github.io/pc-water/projects/albury-06.jpg',
    galleryUrls: [
      'https://goldengraphixstudios.github.io/pc-water/projects/albury-06.jpg',
      'https://goldengraphixstudios.github.io/pc-water/projects/albury-01.jpg',
      'https://goldengraphixstudios.github.io/pc-water/projects/albury-02.jpg',
      'https://goldengraphixstudios.github.io/pc-water/projects/albury-03.jpg',
      'https://goldengraphixstudios.github.io/pc-water/projects/albury-04.jpg',
      'https://goldengraphixstudios.github.io/pc-water/projects/albury-05.jpg',
      'https://goldengraphixstudios.github.io/pc-water/projects/albury-07.jpg',
      'https://goldengraphixstudios.github.io/pc-water/projects/albury-08.jpg',
      'https://goldengraphixstudios.github.io/pc-water/projects/albury-09.jpg',
      'https://goldengraphixstudios.github.io/pc-water/projects/albury-10.jpg',
    ],
    status: 'published',
    featured: false,
    seoTitle: null,
    seoDescription: null,
    publishedAt: '2026-04-04T09:00:00.000Z',
    createdAt: '2026-04-04T09:00:00.000Z',
    updatedAt: '2026-04-04T09:00:00.000Z',
    tags: [
      { id: 'tag-government-3', name: 'Government', slug: 'government' },
      { id: 'tag-rpvc-liners-project', name: 'RPVC Liners', slug: 'rpvc-liners' },
      { id: 'tag-tank-liners', name: 'Tank Liners', slug: 'tank-liners' },
      { id: 'tag-refurbish-2', name: 'Refurbish', slug: 'refurbish' },
    ],
  },
  {
    id: staticId('project', 'Clarence Road Liner Replacement'),
    title: 'Clarence Road Liner Replacement',
    slug: 'clarence-road-liner',
    summary: '2 × tank RPVC liner replacement',
    content:
      'PC Water Infrastructure replaced failing liners for two tanks at 107 Clarence Road, restoring compliant operation and extending usable life.\n\nThis project reflects a common remediation pathway for commercial assets that need practical intervention without full replacement.',
    sector: 'Commercial',
    location: '107 Clarence Road',
    scope: '2 × tank RPVC liner replacement',
    heroImageUrl: 'https://goldengraphixstudios.github.io/pc-water/projects/clarence-01.jpg',
    galleryUrls: [
      'https://goldengraphixstudios.github.io/pc-water/projects/clarence-01.jpg',
      'https://goldengraphixstudios.github.io/pc-water/projects/clarence-02.jpg',
      'https://goldengraphixstudios.github.io/pc-water/projects/clarence-03.jpg',
      'https://goldengraphixstudios.github.io/pc-water/projects/clarence-04.jpg',
      'https://goldengraphixstudios.github.io/pc-water/projects/clarence-05.jpg',
      'https://goldengraphixstudios.github.io/pc-water/projects/clarence-06.jpg',
    ],
    status: 'published',
    featured: false,
    seoTitle: null,
    seoDescription: null,
    publishedAt: '2026-04-05T09:00:00.000Z',
    createdAt: '2026-04-05T09:00:00.000Z',
    updatedAt: '2026-04-05T09:00:00.000Z',
    tags: [
      { id: 'tag-commercial', name: 'Commercial', slug: 'commercial' },
      { id: 'tag-fire-contractors', name: 'Fire Contractors', slug: 'fire-contractors' },
      { id: 'tag-rpvc-liners-project-2', name: 'RPVC Liners', slug: 'rpvc-liners' },
      { id: 'tag-tank-liners-2', name: 'Tank Liners', slug: 'tank-liners' },
    ],
  },
]
